version: "3"
services:
  mongo:
    image: mongo:4.4
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongo/db:/data/db

  meili:
    image: getmeili/meilisearch:v0.20.0
    ports:
      - 127.0.0.1:7700:7700
    volumes:
      - ./meili/data:/data.ms
